@echo off
setlocal

set "GIT_BASH=%CODEX_GIT_BASH%"
if not defined GIT_BASH set "GIT_BASH=C:\Program Files\Git\bin\bash.exe"
if not exist "%GIT_BASH%" (
  echo Git Bash not found. Set CODEX_GIT_BASH to your bash.exe path. 1>&2
  exit /b 1
)

set "SAFE_BASH_ENV=%TEMP%\codex-safe-bash-env.sh"
> "%SAFE_BASH_ENV%" echo # Generated by scripts/windows/bash-safe.cmd
>>"%SAFE_BASH_ENV%" echo # Keep the current Windows/MSVC toolchain PATH, but drop Git/MSYS bins that shadow link.exe.
>>"%SAFE_BASH_ENV%" echo sanitize_path^(^) {
>>"%SAFE_BASH_ENV%" echo   local IFS=':'
>>"%SAFE_BASH_ENV%" echo   local kept=^(^)
>>"%SAFE_BASH_ENV%" echo   local entry
>>"%SAFE_BASH_ENV%" echo   for entry in $PATH; do
>>"%SAFE_BASH_ENV%" echo     case "$entry" in
>>"%SAFE_BASH_ENV%" echo       /usr/bin^|/bin^|/usr/local/bin^|/mingw64/bin^|/mingw32/bin) ;;
>>"%SAFE_BASH_ENV%" echo       *) kept+=("$entry") ;;
>>"%SAFE_BASH_ENV%" echo     esac
>>"%SAFE_BASH_ENV%" echo   done
>>"%SAFE_BASH_ENV%" echo   local joined=""
>>"%SAFE_BASH_ENV%" echo   local item
>>"%SAFE_BASH_ENV%" echo   for item in "${kept[@]}"; do
>>"%SAFE_BASH_ENV%" echo     if [[ -n "$joined" ]]; then
>>"%SAFE_BASH_ENV%" echo       joined+=":$item"
>>"%SAFE_BASH_ENV%" echo     else
>>"%SAFE_BASH_ENV%" echo       joined="$item"
>>"%SAFE_BASH_ENV%" echo     fi
>>"%SAFE_BASH_ENV%" echo   done
>>"%SAFE_BASH_ENV%" echo   export PATH="$joined"
>>"%SAFE_BASH_ENV%" echo }
>>"%SAFE_BASH_ENV%" echo sanitize_path

set "BASH_ENV=%SAFE_BASH_ENV%"
"%GIT_BASH%" --noprofile --norc %*
exit /b %errorlevel%
